name: monoenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=1.2.0=pyhd8ed1ab_0
  - aiohttp=3.7.0=py39h07f9747_0
  - anyio=3.5.0=py39h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=3.0.1=py_1000
  - attrs=22.1.0=pyh71513ae_1
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py_1
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.9.14=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - chardet=3.0.4=py39h079e4ff_1008
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=py39hf3d152e_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - commonmark=0.9.1=py_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask-core=2022.7.0=py39h06a4308_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fsspec=2022.7.1=pyhd8ed1ab_0
  - future=0.18.2=py39hf3d152e_5
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.11.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.38.1=py39hff7568b_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.19.3=py39h06a4308_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py39h06a4308_0
  - ipython=8.4.0=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0=py39h06a4308_0
  - jupyter_client=7.3.4=py39h06a4308_0
  - jupyter_core=4.10.0=py39h06a4308_0
  - jupyter_server=1.18.1=py39h06a4308_0
  - jupyterlab=3.4.4=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.12.0=py39h06a4308_0
  - kiwisolver=1.4.2=py39h295c915_0
  - kornia=0.6.6=pyhd8ed1ab_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.18.0=h780b84a_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - locket=1.0.0=py39h06a4308_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib=3.5.2=py39h06a4308_0
  - matplotlib-base=3.5.2=py39hf590b9c_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=6.0.2=py39hb9d737c_1
  - munkres=1.1.4=py_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.4.4=py39h06a4308_0
  - nbformat=5.3.0=py39h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py39h06a4308_0
  - notebook=6.4.12=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpy=1.21.5=py39h6c91a56_3
  - numpy-base=1.21.5=py39ha15fc14_3
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py39h8c16a72_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.1.2=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - ply=3.11=py39h06a4308_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.18.0=py39he80948d_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydeprecate=0.3.1=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.4.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - pytest=7.1.2=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-lmdb=1.3.0=py39he80948d_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-lightning=1.5.8=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py39h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.3.0=py39h7f8727e_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py39h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rich=12.5.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-image=0.16.2=py39ha9443f7_0
  - scikit-learn=1.1.1=py39h6a678d5_0
  - scipy=1.7.3=py39h6c91a56_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=63.4.1=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39h06a4308_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.39.2=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.10.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py39hd97740a_2
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - terminado=0.13.1=py39h06a4308_0
  - testpath=0.6.0=py39h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchmetrics=0.9.3=pyhd8ed1ab_0
  - torchvision=0.13.1=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=py39h06a4308_0
  - typing_extensions=4.3.0=py39h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.11=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py39hb9d737c_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - opencv-python-headless==4.6.0.66
    - timm==0.6.7
